name: Websend
main: websend.Main
version: 0.9
description: Plug-in to enable variables-transfer to the interwebs and backwards.
author: Waterflames
commands:
   websend:
      description: Sends variables to server.
      usage: |
              /<command> <arguments>
   ws:
      description: Sends variables to server.
      usage: |
              /<command> <arguments>